name: base

services:
    cfnview:
        container_name: ${PREFIX}-cfnview
        build:
            context: ..
            args:
                SF6_COOKIE: ${SF6_COOKIE}
                DATABASE_URL: ${DATABASE_URL}
        ports:
            - "6768:3000"
        restart: unless-stopped
