name: base

services:
    cfnview:
        container_name: ${PREFIX}-cfnview
        build:
            context: ..
            args:
                GO_API_URL: ${GO_API_URL}
        ports:
            - "6768:3000"
        restart: unless-stopped
        environment:
            NODE_OPTIONS: "--dns-result-order=ipv4first"
